[tool.poetry]
name = "depositaire"
version = "0.1.0"
description = "A share registrar solution for the 21st century."
authors = ["Nick Schlobohm <nickschlobohm@protonmail.ch>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^1.1.2"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
